
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.aaeitems.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.aaeitems.item.UncookedPizzaItem;
import net.mcreator.aaeitems.item.TrueBanHammerPixelItem;
import net.mcreator.aaeitems.item.TrueBanHammerNCMDPixelItem;
import net.mcreator.aaeitems.item.TrueBanHammerNCMDItem;
import net.mcreator.aaeitems.item.TrueBanHammerItem;
import net.mcreator.aaeitems.item.TesterItem;
import net.mcreator.aaeitems.item.PizzaSliceItem;
import net.mcreator.aaeitems.item.OperatorsShovelItem;
import net.mcreator.aaeitems.item.OperatorsPickaxeItem;
import net.mcreator.aaeitems.item.OperatorsItem;
import net.mcreator.aaeitems.item.OperatorsHoeItem;
import net.mcreator.aaeitems.item.OperatorsAxeItem;
import net.mcreator.aaeitems.item.MiniBanHammerPixelItem;
import net.mcreator.aaeitems.item.MiniBanHammerItem;
import net.mcreator.aaeitems.item.KickBanHammerPixelItem;
import net.mcreator.aaeitems.item.KickBanHammerItem;
import net.mcreator.aaeitems.item.EnragedEngieShovelItem;
import net.mcreator.aaeitems.item.EnragedEngiePickaxeItem;
import net.mcreator.aaeitems.item.EnragedEngieItem;
import net.mcreator.aaeitems.item.EnragedEngieHoeItem;
import net.mcreator.aaeitems.item.EnragedEngieEssenceItem;
import net.mcreator.aaeitems.item.EnragedEngieAxeItem;
import net.mcreator.aaeitems.item.EngiesScytheItem;
import net.mcreator.aaeitems.item.EngieShovelItem;
import net.mcreator.aaeitems.item.EngiePickaxeItem;
import net.mcreator.aaeitems.item.EngieItem;
import net.mcreator.aaeitems.item.EngieHoeItem;
import net.mcreator.aaeitems.item.EngieGemItem;
import net.mcreator.aaeitems.item.EngieAxeItem;
import net.mcreator.aaeitems.item.EngiShovelItem;
import net.mcreator.aaeitems.item.EngiPickaxeItem;
import net.mcreator.aaeitems.item.EngiAxeItem;
import net.mcreator.aaeitems.item.EmptyCheesePuffsBinItem;
import net.mcreator.aaeitems.item.EchdeathPixelItem;
import net.mcreator.aaeitems.item.EchdeathItem;
import net.mcreator.aaeitems.item.DoughWithSauceItem;
import net.mcreator.aaeitems.item.DoughItem;
import net.mcreator.aaeitems.item.DeveloperItem;
import net.mcreator.aaeitems.item.CrucifixItem;
import net.mcreator.aaeitems.item.CrackersInBowlItem;
import net.mcreator.aaeitems.item.CrackerDustItem;
import net.mcreator.aaeitems.item.CookedPizzaItem;
import net.mcreator.aaeitems.item.ContributorItem;
import net.mcreator.aaeitems.item.CheesePuffsUnopenedItem;
import net.mcreator.aaeitems.item.CheesePuffsOpenedItem;
import net.mcreator.aaeitems.item.CheeseItem;
import net.mcreator.aaeitems.item.BiggestBanHammerPixelItem;
import net.mcreator.aaeitems.item.BiggestBanHammerItem;
import net.mcreator.aaeitems.item.BiggerBanHammerPixelItem;
import net.mcreator.aaeitems.item.BiggerBanHammerItem;
import net.mcreator.aaeitems.item.BigBanHammerPixelItem;
import net.mcreator.aaeitems.item.BigBanHammerItem;
import net.mcreator.aaeitems.item.BanHammerPixelItem;
import net.mcreator.aaeitems.item.BanHammerItem;
import net.mcreator.aaeitems.item.AngryEngieShovelItem;
import net.mcreator.aaeitems.item.AngryEngiePickaxeItem;
import net.mcreator.aaeitems.item.AngryEngieItem;
import net.mcreator.aaeitems.item.AngryEngieHoeItem;
import net.mcreator.aaeitems.item.AngryEngieEssenceItem;
import net.mcreator.aaeitems.item.AngryEngieAxeItem;
import net.mcreator.aaeitems.item.AAEEngieItem;
import net.mcreator.aaeitems.AaeItemsMod;

public class AaeItemsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, AaeItemsMod.MODID);
	public static final RegistryObject<Item> ANGRY_ENGIE_ESSENCE = REGISTRY.register("angry_engie_essence", () -> new AngryEngieEssenceItem());
	public static final RegistryObject<Item> ENGIE_GEM = REGISTRY.register("engie_gem", () -> new EngieGemItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_ESSENCE = REGISTRY.register("enraged_engie_essence", () -> new EnragedEngieEssenceItem());
	public static final RegistryObject<Item> ENGIE_HELMET = REGISTRY.register("engie_helmet", () -> new EngieItem.Helmet());
	public static final RegistryObject<Item> ENGIE_CHESTPLATE = REGISTRY.register("engie_chestplate", () -> new EngieItem.Chestplate());
	public static final RegistryObject<Item> ENGIE_LEGGINGS = REGISTRY.register("engie_leggings", () -> new EngieItem.Leggings());
	public static final RegistryObject<Item> ENGIE_BOOTS = REGISTRY.register("engie_boots", () -> new EngieItem.Boots());
	public static final RegistryObject<Item> ANGRY_ENGIE_HELMET = REGISTRY.register("angry_engie_helmet", () -> new AngryEngieItem.Helmet());
	public static final RegistryObject<Item> ANGRY_ENGIE_CHESTPLATE = REGISTRY.register("angry_engie_chestplate", () -> new AngryEngieItem.Chestplate());
	public static final RegistryObject<Item> ANGRY_ENGIE_LEGGINGS = REGISTRY.register("angry_engie_leggings", () -> new AngryEngieItem.Leggings());
	public static final RegistryObject<Item> ANGRY_ENGIE_BOOTS = REGISTRY.register("angry_engie_boots", () -> new AngryEngieItem.Boots());
	public static final RegistryObject<Item> ENGIE_BLOCK = block(AaeItemsModBlocks.ENGIE_BLOCK, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ANGRY_ENGIE_BLOCK = block(AaeItemsModBlocks.ANGRY_ENGIE_BLOCK, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ENRAGED_ENGIE_BLOCK = block(AaeItemsModBlocks.ENRAGED_ENGIE_BLOCK, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ENGIE_ORE = block(AaeItemsModBlocks.ENGIE_ORE, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> DEEPSLATE_ENGIE_ORE = block(AaeItemsModBlocks.DEEPSLATE_ENGIE_ORE, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_TABLE = block(AaeItemsModBlocks.METAL_TABLE, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> OLD_ENGIE_ORE = block(AaeItemsModBlocks.OLD_ENGIE_ORE, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> OLD_DEEPSLATE_ENGIE_ORE = block(AaeItemsModBlocks.OLD_DEEPSLATE_ENGIE_ORE, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> CRUCIFIX = REGISTRY.register("crucifix", () -> new CrucifixItem());
	public static final RegistryObject<Item> MINI_BAN_HAMMER = REGISTRY.register("mini_ban_hammer", () -> new MiniBanHammerItem());
	public static final RegistryObject<Item> BAN_HAMMER = REGISTRY.register("ban_hammer", () -> new BanHammerItem());
	public static final RegistryObject<Item> BIG_BAN_HAMMER = REGISTRY.register("big_ban_hammer", () -> new BigBanHammerItem());
	public static final RegistryObject<Item> BIGGER_BAN_HAMMER = REGISTRY.register("bigger_ban_hammer", () -> new BiggerBanHammerItem());
	public static final RegistryObject<Item> BIGGEST_BAN_HAMMER = REGISTRY.register("biggest_ban_hammer", () -> new BiggestBanHammerItem());
	public static final RegistryObject<Item> TRUE_BAN_HAMMER_NCMD = REGISTRY.register("true_ban_hammer_ncmd", () -> new TrueBanHammerNCMDItem());
	public static final RegistryObject<Item> MINI_BAN_HAMMER_PIXEL = REGISTRY.register("mini_ban_hammer_pixel", () -> new MiniBanHammerPixelItem());
	public static final RegistryObject<Item> BAN_HAMMER_PIXEL = REGISTRY.register("ban_hammer_pixel", () -> new BanHammerPixelItem());
	public static final RegistryObject<Item> BIG_BAN_HAMMER_PIXEL = REGISTRY.register("big_ban_hammer_pixel", () -> new BigBanHammerPixelItem());
	public static final RegistryObject<Item> BIGGER_BAN_HAMMER_PIXEL = REGISTRY.register("bigger_ban_hammer_pixel", () -> new BiggerBanHammerPixelItem());
	public static final RegistryObject<Item> BIGGEST_BAN_HAMMER_PIXEL = REGISTRY.register("biggest_ban_hammer_pixel", () -> new BiggestBanHammerPixelItem());
	public static final RegistryObject<Item> TRUE_BAN_HAMMER_NCMD_PIXEL = REGISTRY.register("true_ban_hammer_ncmd_pixel", () -> new TrueBanHammerNCMDPixelItem());
	public static final RegistryObject<Item> TRUE_BAN_HAMMER = REGISTRY.register("true_ban_hammer", () -> new TrueBanHammerItem());
	public static final RegistryObject<Item> KICK_BAN_HAMMER = REGISTRY.register("kick_ban_hammer", () -> new KickBanHammerItem());
	public static final RegistryObject<Item> ECHDEATH = REGISTRY.register("echdeath", () -> new EchdeathItem());
	public static final RegistryObject<Item> TRUE_BAN_HAMMER_PIXEL = REGISTRY.register("true_ban_hammer_pixel", () -> new TrueBanHammerPixelItem());
	public static final RegistryObject<Item> KICK_BAN_HAMMER_PIXEL = REGISTRY.register("kick_ban_hammer_pixel", () -> new KickBanHammerPixelItem());
	public static final RegistryObject<Item> ECHDEATH_PIXEL = REGISTRY.register("echdeath_pixel", () -> new EchdeathPixelItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_HELMET = REGISTRY.register("enraged_engie_helmet", () -> new EnragedEngieItem.Helmet());
	public static final RegistryObject<Item> ENRAGED_ENGIE_CHESTPLATE = REGISTRY.register("enraged_engie_chestplate", () -> new EnragedEngieItem.Chestplate());
	public static final RegistryObject<Item> ENRAGED_ENGIE_LEGGINGS = REGISTRY.register("enraged_engie_leggings", () -> new EnragedEngieItem.Leggings());
	public static final RegistryObject<Item> ENRAGED_ENGIE_BOOTS = REGISTRY.register("enraged_engie_boots", () -> new EnragedEngieItem.Boots());
	public static final RegistryObject<Item> ENGIE_AXE = REGISTRY.register("engie_axe", () -> new EngieAxeItem());
	public static final RegistryObject<Item> ENGIE_PICKAXE = REGISTRY.register("engie_pickaxe", () -> new EngiePickaxeItem());
	public static final RegistryObject<Item> ENGIE_SHOVEL = REGISTRY.register("engie_shovel", () -> new EngieShovelItem());
	public static final RegistryObject<Item> ENGIE_HOE = REGISTRY.register("engie_hoe", () -> new EngieHoeItem());
	public static final RegistryObject<Item> OPERATORS_HELMET = REGISTRY.register("operators_helmet", () -> new OperatorsItem.Helmet());
	public static final RegistryObject<Item> OPERATORS_CHESTPLATE = REGISTRY.register("operators_chestplate", () -> new OperatorsItem.Chestplate());
	public static final RegistryObject<Item> OPERATORS_LEGGINGS = REGISTRY.register("operators_leggings", () -> new OperatorsItem.Leggings());
	public static final RegistryObject<Item> OPERATORS_BOOTS = REGISTRY.register("operators_boots", () -> new OperatorsItem.Boots());
	public static final RegistryObject<Item> ANGRY_ENGIE_AXE = REGISTRY.register("angry_engie_axe", () -> new AngryEngieAxeItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_PICKAXE = REGISTRY.register("angry_engie_pickaxe", () -> new AngryEngiePickaxeItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_SHOVEL = REGISTRY.register("angry_engie_shovel", () -> new AngryEngieShovelItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_HOE = REGISTRY.register("angry_engie_hoe", () -> new AngryEngieHoeItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_AXE = REGISTRY.register("enraged_engie_axe", () -> new EnragedEngieAxeItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_PICKAXE = REGISTRY.register("enraged_engie_pickaxe", () -> new EnragedEngiePickaxeItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_SHOVEL = REGISTRY.register("enraged_engie_shovel", () -> new EnragedEngieShovelItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_HOE = REGISTRY.register("enraged_engie_hoe", () -> new EnragedEngieHoeItem());
	public static final RegistryObject<Item> ENGI_AXE = REGISTRY.register("engi_axe", () -> new EngiAxeItem());
	public static final RegistryObject<Item> ENGI_PICKAXE = REGISTRY.register("engi_pickaxe", () -> new EngiPickaxeItem());
	public static final RegistryObject<Item> ENGI_SHOVEL = REGISTRY.register("engi_shovel", () -> new EngiShovelItem());
	public static final RegistryObject<Item> THANKS_FOR_PLAYING = block(AaeItemsModBlocks.THANKS_FOR_PLAYING, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ENGIES_SCYTHE = REGISTRY.register("engies_scythe", () -> new EngiesScytheItem());
	public static final RegistryObject<Item> DOUGH = REGISTRY.register("dough", () -> new DoughItem());
	public static final RegistryObject<Item> DOUGH_WITH_SAUCE = REGISTRY.register("dough_with_sauce", () -> new DoughWithSauceItem());
	public static final RegistryObject<Item> UNCOOKED_PIZZA = REGISTRY.register("uncooked_pizza", () -> new UncookedPizzaItem());
	public static final RegistryObject<Item> COOKED_PIZZA = REGISTRY.register("cooked_pizza", () -> new CookedPizzaItem());
	public static final RegistryObject<Item> PIZZA_SLICE = REGISTRY.register("pizza_slice", () -> new PizzaSliceItem());
	public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new CheeseItem());
	public static final RegistryObject<Item> CRACKERS_IN_BOWL = REGISTRY.register("crackers_in_bowl", () -> new CrackersInBowlItem());
	public static final RegistryObject<Item> CRACKER_DUST = REGISTRY.register("cracker_dust", () -> new CrackerDustItem());
	public static final RegistryObject<Item> OPERATORS_AXE = REGISTRY.register("operators_axe", () -> new OperatorsAxeItem());
	public static final RegistryObject<Item> OPERATORS_PICKAXE = REGISTRY.register("operators_pickaxe", () -> new OperatorsPickaxeItem());
	public static final RegistryObject<Item> OPERATORS_SHOVEL = REGISTRY.register("operators_shovel", () -> new OperatorsShovelItem());
	public static final RegistryObject<Item> OPERATORS_HOE = REGISTRY.register("operators_hoe", () -> new OperatorsHoeItem());
	public static final RegistryObject<Item> CHEESE_PUFFS_UNOPENED = REGISTRY.register("cheese_puffs_unopened", () -> new CheesePuffsUnopenedItem());
	public static final RegistryObject<Item> EMPTY_CHEESE_PUFFS_BIN = REGISTRY.register("empty_cheese_puffs_bin", () -> new EmptyCheesePuffsBinItem());
	public static final RegistryObject<Item> CHEESE_PUFFS_OPENED = REGISTRY.register("cheese_puffs_opened", () -> new CheesePuffsOpenedItem());
	public static final RegistryObject<Item> METAL_CHEST = block(AaeItemsModBlocks.METAL_CHEST, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_OAK = block(AaeItemsModBlocks.METAL_CHEST_OAK, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> DEVELOPER_HELMET = REGISTRY.register("developer_helmet", () -> new DeveloperItem.Helmet());
	public static final RegistryObject<Item> DEVELOPER_CHESTPLATE = REGISTRY.register("developer_chestplate", () -> new DeveloperItem.Chestplate());
	public static final RegistryObject<Item> DEVELOPER_LEGGINGS = REGISTRY.register("developer_leggings", () -> new DeveloperItem.Leggings());
	public static final RegistryObject<Item> DEVELOPER_BOOTS = REGISTRY.register("developer_boots", () -> new DeveloperItem.Boots());
	public static final RegistryObject<Item> IDEAGIVER_HELMET = REGISTRY.register("ideagiver_helmet", () -> new ContributorItem.Helmet());
	public static final RegistryObject<Item> IDEAGIVER_CHESTPLATE = REGISTRY.register("ideagiver_chestplate", () -> new ContributorItem.Chestplate());
	public static final RegistryObject<Item> IDEAGIVER_LEGGINGS = REGISTRY.register("ideagiver_leggings", () -> new ContributorItem.Leggings());
	public static final RegistryObject<Item> IDEAGIVER_BOOTS = REGISTRY.register("ideagiver_boots", () -> new ContributorItem.Boots());
	public static final RegistryObject<Item> ENGIE_GAMES_GUI_SPAWN_EGG = REGISTRY.register("engie_games_gui_spawn_egg", () -> new ForgeSpawnEggItem(AaeItemsModEntities.ENGIE_GAMES_GUI, -10763008, -1194203, new Item.Properties().tab(null)));
	public static final RegistryObject<Item> METAL_CHEST_DARK_OAK = block(AaeItemsModBlocks.METAL_CHEST_DARK_OAK, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_SPRUCE = block(AaeItemsModBlocks.METAL_CHEST_SPRUCE, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_ACACIA = block(AaeItemsModBlocks.METAL_CHEST_ACACIA, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_BIRCH = block(AaeItemsModBlocks.METAL_CHEST_BIRCH, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_WARPED = block(AaeItemsModBlocks.METAL_CHEST_WARPED, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_CRIMSON = block(AaeItemsModBlocks.METAL_CHEST_CRIMSON, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_JUNGLE = block(AaeItemsModBlocks.METAL_CHEST_JUNGLE, AaeItemsModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> TESTER_HELMET = REGISTRY.register("tester_helmet", () -> new TesterItem.Helmet());
	public static final RegistryObject<Item> TESTER_CHESTPLATE = REGISTRY.register("tester_chestplate", () -> new TesterItem.Chestplate());
	public static final RegistryObject<Item> TESTER_LEGGINGS = REGISTRY.register("tester_leggings", () -> new TesterItem.Leggings());
	public static final RegistryObject<Item> TESTER_BOOTS = REGISTRY.register("tester_boots", () -> new TesterItem.Boots());
	public static final RegistryObject<Item> AAE_ENGIE = REGISTRY.register("aae_engie", () -> new AAEEngieItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
