modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="aae_items"
version="10.19.24"
displayName="AAE Items"
credits="Find the book."
displayURL="https://www.twitch.tv/engiegames"
logoFile="logo.png"
authors="EngieGames"
description="Made with MCreator."

[[dependencies.aae_items]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




